apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-nodejs.name" . }}-secret
  labels:
    {{- include "sample-nodejs.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
